### ISSUE TITLE
preload failure when running cloud suite with make local-test

### ISSUE THREAD

**Issue by rcooke-warwick** [balena-os/leviathan#839]
WHen using the qemu worker locally (not jenkins), preloading fails:

```
client_1  | [2022-11-09T10:38:08.965Z][worker-cloud]
client_1  | [2022-11-09T10:38:15.441Z][worker-cloud] Waiting for Docker to start...
client_1  | [2022-11-09T10:38:18.169Z][worker-cloud] Docker started
client_1  | [2022-11-09T10:38:23.670Z][worker-cloud]
client_1  | Retrying (count=2) /sbin/losetup -f --show /dev/loop13 False
client_1  | Hint: If using a Virtual Machine, consider increasing the number of processors.
client_1  | If using Docker Desktop for Windows or macOS, it may require restarting.
client_1  | [2022-11-09T10:38:30.189Z][worker-cloud]
client_1  | Retrying (count=3) /sbin/losetup -f --show /dev/loop13 False
client_1  | Hint: If using a Virtual Machine, consider increasing the number of processors.
client_1  | If using Docker Desktop for Windows or macOS, it may require restarting.
client_1  | [2022-11-09T10:38:42.714Z][worker-cloud]
client_1  | Retrying (count=4) /sbin/losetup -f --show /dev/loop13 False
client_1  | Hint: If using a Virtual Machine, consider increasing the number of processors.
client_1  | If using Docker Desktop for Windows or macOS, it may require restarting.
client_1  | [2022-11-09T10:39:07.264Z][worker-cloud]
client_1  | Retrying (count=5) /sbin/losetup -f --show /dev/loop13 False
client_1  | Hint: If using a Virtual Machine, consider increasing the number of processors.
client_1  | If using Docker Desktop for Windows or macOS, it may require restarting.
```

**Comment by rcooke-warwick** [comment]
current workaround, is to change `docker-compse.client.yml` locally:
```
core:
    privileged: true # preload requires docker-in-docker
    build: core
    volumes:
      - core-storage:/data
      - reports-storage:/reports
      - /dev:/dev # required for creating losetup devices during preload
    tmpfs:
      - /var/run # use tmpfs docker-in-docker pid files
      - /var/lib/docker use tmpfs for docker-in-docker data root
    restart: 'no'
```

Moving the `/dev:/dev` bind mount  away from the `devices` attribute of the yml file

I'm not sure why this works yet
